version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    networks:
      - rag_network
    ports:
      - "6379:6379"

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - rag_network

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    networks:
      - rag_network

  milvus:
    image: "milvusdb/milvus:v2.4.15"
    container_name: milvus
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    networks:
      - rag_network
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    depends_on:
      - etcd
      - minio

  rag_service:
    build: .
    container_name: rag_service
    depends_on:
      - redis
      - milvus
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - MILVUS_URI=http://milvus:19530
      - MILVUS_TOKEN=root:Milvus
    networks:
      - rag_network
    ports:
      - "5001:5000"

  attu:
    image: zilliz/attu:v2.4.11
    container_name: attu
    environment:
      - MILVUS_URL=milvus:19530
    networks:
      - rag_network
    ports:
      - "8000:3000"
    depends_on:
      - milvus

networks:
  rag_network:
    driver: bridge

volumes:
  milvus_data:
  etcd_data:
  minio_data:
