version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    networks:
      - rag_network
    ports:
      - "6379:6379"

  milvus:
    image: "milvusdb/milvus:v2.4.0"
    container_name: milvus
    networks:
      - rag_network
    ports:
      - "19530:19530"
    environment:
      - ETCD_CFG.endpoints=etcd:2379
      - MINIO_ADDRESS=minio:9000
    volumes:
      - milvus_data:/var/lib/milvus

  rag_service:
    build: .
    container_name: rag_service
    depends_on:
      - redis
      - milvus
    environment:
      - REDIS_URL=${REDIS_URL:-redis:6379}
      - MILVUS_URI=http://milvus:19530
      - MILVUS_TOKEN=root:Milvus
    networks:
      - rag_network
    ports:
      - "5000:5000"

networks:
  rag_network:
    driver: bridge

volumes:
  milvus_data:
